#!/bin/bash
#由于现在Linux服务器系统都是采用Kickstart批量最小化安装，需要进行系统安全加固及优化
#下载yum配置文件到本地代替系统默认yum源
#this script is only for CentOS 6.x
platform=`uname -i`
if [ $platform != "x86_64" ];then 
echo "this script is only for 64bit Operating System !"
exit 1
fi
echo "the platform is ok"
cat << EOF
+---------------------------------------+
|   your system is x86_64      |
|      start optimizing.......          |
+---------------------------------------
EOF
##optimize 6
cd /etc/yum.repos.d/
mkdir bak
mv CentOS-*.repo  bak
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-6.repo
rpm -ivh http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
yum clean all
yum makecache
#安装系统补丁
yum  -y update glibc glibc-devel glibc-common glibc-headers bash
#安装gcc基础库文件以及sysstat工具
yum -y install gcc gcc-c++ vim-enhanced zip unzip  sysstat cmake pcre-devel wget dos2unix ntpdate
#配置ntpdate自动对时
yum -y install ntp
echo "01 */5 * * * /usr/sbin/ntpdate time.apple.com;/usr/sbin/hwclock -w  >> /dev/null 2>&1" >> /etc/crontab
ntpdate time.apple.com
service crond restart
#配置文件的ulimit值
echo  "* soft nofile 200000">>/etc/security/limits.conf
echo  "* hard nofile 200000" >>/etc/security/limits.conf
echo  "* soft nproc 200000">>/etc/security/limits.conf
echo  "* hard nproc 200000" >>/etc/security/limits.conf
sed -i 's/1024/10240/' /etc/security/limits.d/90-nproc.conf
ulimit -SHn 200000
#tune kernel parametres(基础系统内核优化)
#web篇 
cat >> /etc/sysctl.conf << EOF
net.ipv4.ip_forward = 1  
net.ipv4.conf.default.rp_filter = 1  
net.ipv4.conf.default.accept_source_route = 0  
kernel.sysrq = 0  
kernel.core_uses_pid = 1  
net.ipv4.tcp_syncookies = 1  
kernel.msgmnb = 65536  
kernel.msgmax = 65536  
kernel.shmmax = 68719476736  
kernel.shmall = 4294967296  
net.ipv4.tcp_max_tw_buckets = 6000  
net.ipv4.tcp_sack = 1  
net.ipv4.tcp_window_scaling = 1  
net.ipv4.tcp_rmem = 4096 87380 4194304   
net.ipv4.tcp_wmem = 4096 16384 4194304   
net.core.wmem_default = 8388608  
net.core.rmem_default = 8388608  
net.core.rmem_max = 16777216  
net.core.wmem_max = 16777216  
net.core.netdev_max_backlog = 262144  
net.core.somaxconn = 20000
net.ipv4.tcp_max_orphans = 3276800  
net.ipv4.tcp_max_syn_backlog = 262144  
net.ipv4.tcp_timestamps = 0  
net.ipv4.tcp_synack_retries = 1  
net.ipv4.tcp_syn_retries = 1  
net.ipv4.tcp_tw_recycle = 1  
net.ipv4.tcp_tw_reuse = 1  
net.ipv4.tcp_mem = 786432 1048576 1572864 
net.ipv4.tcp_fin_timeout = 30  
net.ipv4.tcp_keepalive_time = 60  
net.ipv4.ip_local_port_range = 4096 65000 
net.ipv4.tcp_timestamps=1
vm.overcommit_memory = 1
EOF

#禁用control-alt-delete组合键以防止误操作
sed -i 's@ca::ctrlaltdel:/sbin/shutdown -t3 -r now@#ca::ctrlaltdel:/sbin/shutdown -t3 -r now@' /etc/inittab
#log user used command  to /var/log/message and open files
#加入超时断开及记录用户操作至message日志文件中
cat >>/etc/profile  <<EOF
export PROMPT_COMMAND='{ msg=\$(history 1 | { read x y; echo \$y; });logger "[euid=\$(whoami)]":\$(who am i):[\`pwd\`]"\$msg"; }'
TMOUT=900
EOF
#
#关闭SElinux
sed -i 's@SELINUX=enforcing@SELINUX=disabled@' /etc/selinux/config
#ssh服务配置优化
sed -i 's@#UseDNS yes@UseDNS no@' /etc/ssh/sshd_config
#sed -i  '$ a\Allowusers root@192.168.0.172  root@192.168.30.253 user01 user02 user03'  /etc/ssh/sshd_config
sed -i '/^#Port 22/a Port 10080' /etc/ssh/sshd_config
#sed -i  '1 a\ auth          required        pam_tally2.so        deny=6  unlock_time=300 even_deny_root root_unlock_time=10' /etc/pam.d/sshd
service sshd restart
#vim基础语法优化
sed -i '/set ruler/a set number' /etc/vimrc
sed -i '/set ruler/a set cindent' /etc/vimrc
sed -i '/set ruler/a set autoindent' /etc/vimrc
sed -i '/set ruler/a set shiftwidth=4' /etc/vimrc
sed -i '/set ruler/a set tabstop=4' /etc/vimrc
echo "syntax on" >> /root/.vimrc
echo "set nohlsearch" >> /root/.vimrc
#停用系统中不必要的服务
chkconfig ip6tables off
chkconfig sendmail off
#chkconfig kudzu off
#chkconfig nfslock off
#chkconfig portmap off
#chkconfig autofs off
#cat >> /etc/services << EOF
#zabbix-agent 10050/tcp Zabbix Agent
#zabbix-agent 10050/tcp Zabbix Agent
#zabbix-trapper 10051/tcp Zabbix Trapper
#zabbix-trapper 10051/tcp Zabbix Trapper
#EOF
#iptables 配置
cat >  /etc/sysconfig/iptables  << EOF 
# Generated by iptables-save v1.4.7 on Sat Apr 21 13:20:07 2018
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1:152]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p icmp -j ACCEPT 
-A INPUT -i lo -j ACCEPT 
-A INPUT -s 39.108.224.91/32 -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 10008 -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -j REJECT --reject-with icmp-host-prohibited 
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT 
COMMIT
# Completed on Sat Apr 21 13:20:07 2018 
EOF
/etc/init.d/iptables restart
cat << EOF
+-------------------------------------------------+
|               optimizer is done                 |
|   it's recommond to restart this server !       |
+-------------------------------------------------+
EOF
#重启服务器
echo -n "Do you want restart system? input y/n!!!"
read  choice
if [ $choice == 'y' ];then
reboot
else
exit
fi
