  - name: Delete Mysql compression Software In Redhat Client
    shell: rm -rf /tmp/{{ mysql_file }} /tmp/mysql_security.sh {{ mysql_makedir }}/{{ mysql_version }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
