galaxy_info:
  author: Yang zhi min
  description: Install initializtion Software
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: CentOS
    versions:
    - 5
    - 6
  - name: Ubuntu
    versions:
    - precise
  categories:
  - system
dependencies: []
