galaxy_info:
  author: Yang zhi min
  description: Install Tomcat
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: CentOS
    versions:
    - 6
  categories:
  - Service
dependencies: []
