  - name: Delete Nginx compression Software In Redhat Client
    shell: rm -rf  {{ nginx_makedir }}{{ nginx_version }} /tmp/nginx.conf  /tmp/{{ nginx_version }}.tar.gz
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
